### ISSUE TITLE
unable to use mysql2 0.4.X

### ISSUE THREAD

**Issue by giamma13** [janko-m/sinatra-activerecord#60]
If I upgrade mysql2 to 0.4.X, I get an error:

```ruby
/home/bewe/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.0/lib/active_record/connection_adapters/connection_specification.rb:177:in `rescue in spec': Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
	from /home/bewe/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.0/lib/active_record/connection_adapters/connection_specification.rb:174:in `spec'
	from /home/bewe/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:50:in `establish_connection'
	from /home/bewe/.rvm/gems/ruby-2.2.3/gems/sinatra-activerecord-2.0.9/lib/sinatra/activerecord.rb:45:in `database='
	from /home/bewe/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1217:in `set'
	from /home/bewe/.rvm/gems/ruby-2.2.3/gems/sinatra-activerecord-2.0.9/lib/sinatra/activerecord.rb:39:in `database_file='
	from /home/bewe/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1217:in `set'
	from /home/bewe/.rvm/gems/ruby-2.2.3/gems/sinatra-activerecord-2.0.9/lib/sinatra/activerecord.rb:22:in `registered'
	from /home/bewe/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1400:in `block in register'
	from /home/bewe/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1398:in `each'
	from /home/bewe/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1398:in `register'
	from /home/bewe/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:1969:in `register'
	from /home/bewe/.rvm/gems/ruby-2.2.3/gems/sinatra-1.4.7/lib/sinatra/base.rb:2030:in `register'
	from /home/bewe/.rvm/gems/ruby-2.2.3/gems/sinatra-activerecord-2.0.9/lib/sinatra/activerecord.rb:58:in `<module:Sinatra>'
	from /home/bewe/.rvm/gems/ruby-2.2.3/gems/sinatra-activerecord-2.0.9/lib/sinatra/activerecord.rb:10:in `<top (required)>'
	from /home/bewe/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:85:in `require'
	from /home/bewe/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:85:in `rescue in block in require'
	from /home/bewe/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:68:in `block in require'
	from /home/bewe/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /home/bewe/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /home/bewe/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /home/bewe/Data-Platform/user-profile/app/core.rb:7:in `<top (required)>'
	from /home/bewe/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/bewe/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from bin/console:3:in `<main>'
```

Somehow similar to this issue in the Rails world:
* http://stackoverflow.com/questions/32457657/rails-4-gemloaderror-specified-mysql2-for-database-adapter-but-the-gem-i

**Comment by janko-m** [comment]
Did you add the `mysql2` gem to your Gemfile, like it suggests in the error message? In any way, I know for sure that this is not a bug in sinatra-activerecord.

**Comment by giamma13** [comment]
Yes yes I do have mysql2 in the Gemfile.

But sinatra-activerecord is requiring activerecord 4.2.0.
And these is a bug in activerecord 4.2.0, so that its not allowing to use mysql2 0.4.X (see the above article).
If I manually update activerecord to 4.2.5.1 (in Gemfile.lock), it works.

**Comment by janko-m** [comment]
Aha, I see. But I don't think that sinatra-activerecord should exclude a specific ActiveRecord version from the requirement if it has a bug.
