### ISSUE TITLE
Unable to use db:migrate or db:create

### ISSUE THREAD

**Issue by sixtyfive** [janko-m/sinatra-activerecord#75]
`Rakefile`:

``` 
[...]
require_relative 'config/app.rb'
require_relative Config.lib_path+'parser.rb'
require 'sinatra/activerecord/rake'

namespace :db do
  task :load_config do
    require Config.lib_path+'server.rb'
  end
end
[...]
```
`server.rb`:

```
[...]
require 'sinatra/activerecord'
[...]
module Textbookr
  class Server < Sinatra::Base
    register Sinatra::ActiveRecordExtension
[...]
```

Console output:

```
$ rake db:migrate
rake aborted!
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class Sinatra::SimpleAuthentication::Models::ActiveRecord::CreateUsers < ActiveRecord::Migration[4.2]
/home/jrs/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.1/lib/active_record/migration.rb:525:in `inherited'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/sinatra-simple-authentication-1.0.0/lib/sinatra/simple_authentication/models/active_record/user.rb:12:in `<module:ActiveRecord>'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/sinatra-simple-authentication-1.0.0/lib/sinatra/simple_authentication/models/active_record/user.rb:10:in `<module:Models>'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/sinatra-simple-authentication-1.0.0/lib/sinatra/simple_authentication/models/active_record/user.rb:9:in `<module:SimpleAuthentication>'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/sinatra-simple-authentication-1.0.0/lib/sinatra/simple_authentication/models/active_record/user.rb:8:in `<module:Sinatra>'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/sinatra-simple-authentication-1.0.0/lib/sinatra/simple_authentication/models/active_record/user.rb:7:in `<top (required)>'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/sinatra-simple-authentication-1.0.0/lib/sinatra/simple_authentication/controllers/session.rb:128:in `load_user_class'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/sinatra-simple-authentication-1.0.0/lib/sinatra/simple_authentication/controllers/session.rb:21:in `registered'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/sinatra-simple-authentication-1.0.0/lib/sinatra/simple-authentication.rb:10:in `registered'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/sinatra-2.0.0/lib/sinatra/base.rb:1412:in `block in register'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/sinatra-2.0.0/lib/sinatra/base.rb:1410:in `each'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/sinatra-2.0.0/lib/sinatra/base.rb:1410:in `register'
/home/jrs/Projects/textbookr/lib/server.rb:16:in `<class:Server>'
/home/jrs/Projects/textbookr/lib/server.rb:13:in `<module:Textbookr>'
/home/jrs/Projects/textbookr/lib/server.rb:12:in `<top (required)>'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/jrs/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
/home/jrs/Projects/textbookr/Rakefile:9:in `block (2 levels) in <top (required)>'
/home/jrs/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => db:load_config
(See full trace by running task with --trace)
```

Not sure if this is an issue with `sinatra-activerecord`, but if it isn't, then what am I doing wrong?

**Comment by sixtyfive** [comment]
Okay, I just found out it has to do with me also registering `Sinatra::SimpleAuthentication`. I'm guessing perhaps that does its own AR init stuff...
